version: "2.4"

services:
    db:
        image: mariadb:latest
        container_name: mariadb
        volumes:
            - /home/shyeon/workspace/mysql/_dbdump:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=mini_twitter
            - MYSQL_USER=root
            - MYSQL_PASSWORD=9838
        ports:
            - "3306:3306"
        healthcheck:
            test: mysql -uroot -p9838 -Dmini_twitter -e"SHOW DATABASES"
            interval: 3s
            timeout: 1s
            retries: 3

    web:
        build:
            context: .
            dockerfile: ./Dockerfile
        image: webapp:test
        container_name: webapp
        volumes:
            - /home/shyeon/workspace/python/BackendWithFlask/app:/app
        ports:
            - "5000:5000"
        command:
            - python
            - app.py
        depends_on:
            db:
                condition: service_healthy
